# PROJECT EULER QUESTION #2


#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def sum_even_fibinacci_numbers():
    fib_seq = 1
    fib_nums = [1, 2]
    sum_nums = 0
    
    for i in range(1000):
        if i == 0 or i == 1:
            pass
        else:
            fib_seq = fib_nums[i-1] + fib_nums[i-2]
            fib_nums.append(fib_seq)

    print(fib_nums[:10]) 

    for num in fib_nums:
       
        if num % 2 == 0:
            sum_nums += num


    print("the sum is", sum_nums)


sum_even_fibinacci_numbers()